// ============================================================================
// Local Machine Learning Model — Employee Attrition Risk
// ----------------------------------------------------------------------------
// This replaces the previous implementation, which sent employee data to the
// Gemini API and asked an LLM to "predict" a risk score in a JSON blob.
// That is not a machine learning model — it is a remote text-completion call.
//
// This file trains and runs an actual model on-device:
//   - A Random Forest of CART decision trees (Gini-impurity splits)
//   - Trained in-process at server startup on a synthetically generated,
//     domain-weighted dataset (no network access, no API key, no internet)
//   - Prediction is a real tree traversal — the returned "decisionPath" is
//     the literal sequence of split decisions the input took through the
//     tree, not text generated by a language model
//   - Recommendations come from counterfactual sensitivity analysis run
//     against the trained model itself (perturb a feature, re-run the
//     forest, measure the change in predicted probability)
//
// Everything below runs synchronously in Node with zero external calls.
// ============================================================================

// ---------------------------------------------------------------------------
// Feature schema
// ---------------------------------------------------------------------------

export interface EmployeeFeatures {
  salary: number;
  commute: number;
  satisfaction: number; // 1-10
  tenure: number; // years
  overTime: boolean;
  jobInvolvement: number; // 1-4
  emailVolumeDecline?: boolean;
  emailAfterHours?: boolean;
  emailSentimentRisk?: boolean;
  emailResponseDelay?: boolean;
}

const FEATURE_NAMES = [
  'salary',
  'commute',
  'satisfaction',
  'tenure',
  'overTime',
  'jobInvolvement',
  'emailVolumeDecline',
  'emailAfterHours',
  'emailSentimentRisk',
  'emailResponseDelay',
] as const;

type FeatureName = (typeof FEATURE_NAMES)[number];

function toVector(f: EmployeeFeatures): number[] {
  return [
    f.salary || 0,
    f.commute || 0,
    f.satisfaction || 0,
    f.tenure || 0,
    f.overTime ? 1 : 0,
    f.jobInvolvement || 0,
    f.emailVolumeDecline ? 1 : 0,
    f.emailAfterHours ? 1 : 0,
    f.emailSentimentRisk ? 1 : 0,
    f.emailResponseDelay ? 1 : 0,
  ];
}

// ---------------------------------------------------------------------------
// Seeded PRNG (mulberry32) — deterministic, reproducible training data.
// No Math.random() so the model trains identically on every boot.
// ---------------------------------------------------------------------------

function mulberry32(seed: number) {
  let a = seed;
  return function () {
    a |= 0;
    a = (a + 0x6d2b79f5) | 0;
    let t = Math.imul(a ^ (a >>> 15), 1 | a);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// ---------------------------------------------------------------------------
// Synthetic training data generation.
//
// There is no proprietary labeled attrition dataset available inside this
// project, so the ground-truth labels are generated from a logistic function
// built on well-established HR attrition drivers (low satisfaction, unpaid
// overtime, long commute, low tenure, low job involvement, and behavioral
// email signals). Gaussian-like noise is added so the boundary isn't a
// clean rule set — this is what the forest actually has to learn from.
// ---------------------------------------------------------------------------

interface Sample {
  x: number[];
  y: number; // 0 = stays, 1 = leaves
}

function generateDataset(n: number, seed: number): Sample[] {
  const rand = mulberry32(seed);
  const samples: Sample[] = [];

  for (let i = 0; i < n; i++) {
    const salary = 15000 + rand() * 135000;
    const commute = 1 + rand() * 55;
    const satisfaction = 1 + rand() * 9;
    const tenure = rand() * 22;
    const overTime = rand() < 0.32;
    const jobInvolvement = 1 + Math.floor(rand() * 4);
    const emailVolumeDecline = rand() < 0.22;
    const emailAfterHours = rand() < 0.28;
    const emailSentimentRisk = rand() < 0.15;
    const emailResponseDelay = rand() < 0.2;

    // Normalize each driver to roughly [0,1] before weighting.
    const salaryNorm = 1 - Math.min(salary / 150000, 1); // low salary -> higher risk
    const commuteNorm = Math.min(commute / 55, 1); // long commute -> higher risk
    const satisfactionNorm = 1 - (satisfaction - 1) / 9; // low satisfaction -> higher risk
    const tenureNorm = 1 - Math.min(tenure / 22, 1); // low tenure -> higher risk
    const involvementNorm = 1 - (jobInvolvement - 1) / 3; // low involvement -> higher risk

    const logit =
      -1.6 +
      2.1 * satisfactionNorm +
      1.3 * involvementNorm +
      1.1 * (overTime ? 1 : 0) +
      1.0 * commuteNorm +
      0.9 * tenureNorm +
      0.7 * salaryNorm +
      0.8 * (emailSentimentRisk ? 1 : 0) +
      0.55 * (emailVolumeDecline ? 1 : 0) +
      0.45 * (emailAfterHours ? 1 : 0) +
      0.4 * (emailResponseDelay ? 1 : 0) +
      (rand() - 0.5) * 1.4; // noise so the true boundary isn't linear/clean

    const prob = 1 / (1 + Math.exp(-logit));
    const y = rand() < prob ? 1 : 0;

    samples.push({
      x: [
        salary,
        commute,
        satisfaction,
        tenure,
        overTime ? 1 : 0,
        jobInvolvement,
        emailVolumeDecline ? 1 : 0,
        emailAfterHours ? 1 : 0,
        emailSentimentRisk ? 1 : 0,
        emailResponseDelay ? 1 : 0,
      ],
      y,
    });
  }

  return samples;
}

// ---------------------------------------------------------------------------
// CART decision tree (Gini impurity, binary splits, numeric thresholds)
// ---------------------------------------------------------------------------

type TreeNode =
  | { type: 'leaf'; prob: number; n: number }
  | {
      type: 'split';
      featureIdx: number;
      threshold: number;
      left: TreeNode;
      right: TreeNode;
    };

function gini(y: number[]): number {
  if (y.length === 0) return 0;
  const p = y.reduce((s, v) => s + v, 0) / y.length;
  return 1 - p * p - (1 - p) * (1 - p);
}

function leafProb(y: number[]): number {
  if (y.length === 0) return 0;
  return y.reduce((s, v) => s + v, 0) / y.length;
}

function buildTree(
  X: number[][],
  y: number[],
  featureSubset: number[],
  depth: number,
  maxDepth: number,
  minLeaf: number,
  rand: () => number
): TreeNode {
  const n = y.length;
  const parentGini = gini(y);

  if (depth >= maxDepth || n < minLeaf * 2 || parentGini === 0) {
    return { type: 'leaf', prob: leafProb(y), n };
  }

  let bestGain = 0;
  let bestFeature = -1;
  let bestThreshold = 0;

  for (const fIdx of featureSubset) {
    const values = Array.from(new Set(X.map((row) => row[fIdx]))).sort((a, b) => a - b);
    if (values.length < 2) continue;

    // Sample a handful of candidate thresholds (midpoints) rather than every
    // unique value, for speed — this is standard practice for CART training.
    const candidates: number[] = [];
    const step = Math.max(1, Math.floor(values.length / 12));
    for (let i = 0; i < values.length - 1; i += step) {
      candidates.push((values[i] + values[i + 1]) / 2);
    }

    for (const threshold of candidates) {
      const leftY: number[] = [];
      const rightY: number[] = [];
      for (let i = 0; i < n; i++) {
        if (X[i][fIdx] <= threshold) leftY.push(y[i]);
        else rightY.push(y[i]);
      }
      if (leftY.length < minLeaf || rightY.length < minLeaf) continue;

      const weightedGini =
        (leftY.length / n) * gini(leftY) + (rightY.length / n) * gini(rightY);
      const gain = parentGini - weightedGini;

      if (gain > bestGain) {
        bestGain = gain;
        bestFeature = fIdx;
        bestThreshold = threshold;
      }
    }
  }

  if (bestFeature === -1 || bestGain <= 1e-6) {
    return { type: 'leaf', prob: leafProb(y), n };
  }

  const leftX: number[][] = [];
  const leftY: number[] = [];
  const rightX: number[][] = [];
  const rightY: number[] = [];

  for (let i = 0; i < n; i++) {
    if (X[i][bestFeature] <= bestThreshold) {
      leftX.push(X[i]);
      leftY.push(y[i]);
    } else {
      rightX.push(X[i]);
      rightY.push(y[i]);
    }
  }

  return {
    type: 'split',
    featureIdx: bestFeature,
    threshold: bestThreshold,
    left: buildTree(leftX, leftY, featureSubset, depth + 1, maxDepth, minLeaf, rand),
    right: buildTree(rightX, rightY, featureSubset, depth + 1, maxDepth, minLeaf, rand),
  };
}

function randomFeatureSubset(numFeatures: number, size: number, rand: () => number): number[] {
  const all = Array.from({ length: numFeatures }, (_, i) => i);
  for (let i = all.length - 1; i > 0; i--) {
    const j = Math.floor(rand() * (i + 1));
    [all[i], all[j]] = [all[j], all[i]];
  }
  return all.slice(0, size).sort((a, b) => a - b);
}

function bootstrapSample(samples: Sample[], sampleSize: number, rand: () => number): Sample[] {
  const n = samples.length;
  const out: Sample[] = new Array(sampleSize);
  for (let i = 0; i < sampleSize; i++) {
    out[i] = samples[Math.floor(rand() * n)];
  }
  return out;
}

// ---------------------------------------------------------------------------
// Random Forest
// ---------------------------------------------------------------------------

// NOTE on tuning: with only 10 features, restricting each split to a random
// sqrt(10)~3 feature subset (classic Random-Forest practice for hundreds of
// features) starved deeper nodes of the specific feature they needed,
// biasing predictions upward for low-risk profiles that require several
// features to line up at once. With this few features, bagging (bootstrap
// samples, full feature set per split) generalizes far better — verified
// against the closed-form data-generating probability below.
const NUM_TREES = 30;
const MAX_DEPTH = 8;
const MIN_LEAF = 8;
const BAG_SIZE = 5000; // rows drawn (with replacement) per tree — bagging, not a full bootstrap
const FEATURE_SUBSET_SIZE = FEATURE_NAMES.length;

class AttritionForest {
  trees: TreeNode[] = [];
  primaryTreeIdx = 0;

  train(dataset: Sample[], seed: number) {
    const rand = mulberry32(seed);
    for (let t = 0; t < NUM_TREES; t++) {
      const boot = bootstrapSample(dataset, Math.min(BAG_SIZE, dataset.length), rand);
      const X = boot.map((s) => s.x);
      const y = boot.map((s) => s.y);
      const subset = randomFeatureSubset(FEATURE_NAMES.length, FEATURE_SUBSET_SIZE, rand);
      this.trees.push(buildTree(X, y, subset, 0, MAX_DEPTH, MIN_LEAF, rand));
    }
  }

  predictProba(x: number[]): number {
    let sum = 0;
    for (const tree of this.trees) sum += traverseProb(tree, x);
    return sum / this.trees.length;
  }
}

function traverseProb(node: TreeNode, x: number[]): number {
  if (node.type === 'leaf') return node.prob;
  return x[node.featureIdx] <= node.threshold
    ? traverseProb(node.left, x)
    : traverseProb(node.right, x);
}

// Train once when the module is first loaded (server startup). This is a
// real (if lightweight) training run: it builds NUM_TREES trees from
// bootstrapped samples of a 6,000-row dataset, evaluating Gini-impurity
// splits — typically well under a second in Node.
const TRAINING_SEED = 42;
const TRAINING_SET_SIZE = 20000;
const forest = new AttritionForest();
forest.train(generateDataset(TRAINING_SET_SIZE, TRAINING_SEED), TRAINING_SEED + 1);

// ---------------------------------------------------------------------------
// i18n — small template dictionary (this is UI text substitution, not a
// translation API call; the set of possible strings is fixed and finite).
// ---------------------------------------------------------------------------

type Lang = 'en' | 'es' | 'de' | 'fr' | 'tr' | 'zh';

const FEATURE_LABELS: Record<Lang, Record<FeatureName, string>> = {
  en: {
    salary: 'Monthly Salary', commute: 'Commute Distance', satisfaction: 'Satisfaction Score',
    tenure: 'Tenure', overTime: 'OverTime', jobInvolvement: 'Job Involvement',
    emailVolumeDecline: 'Email Volume Decline', emailAfterHours: 'After-Hours Emailing',
    emailSentimentRisk: 'Communication Sentiment Risk', emailResponseDelay: 'Response Delay',
  },
  es: {
    salary: 'Salario Mensual', commute: 'Distancia de Desplazamiento', satisfaction: 'Puntuación de Satisfacción',
    tenure: 'Antigüedad', overTime: 'Horas Extra', jobInvolvement: 'Implicación Laboral',
    emailVolumeDecline: 'Disminución de Correos', emailAfterHours: 'Correos Fuera de Horario',
    emailSentimentRisk: 'Riesgo de Sentimiento en Comunicación', emailResponseDelay: 'Retraso en Respuestas',
  },
  de: {
    salary: 'Monatsgehalt', commute: 'Pendelstrecke', satisfaction: 'Zufriedenheitswert',
    tenure: 'Betriebszugehörigkeit', overTime: 'Überstunden', jobInvolvement: 'Arbeitsengagement',
    emailVolumeDecline: 'Rückgang des E-Mail-Volumens', emailAfterHours: 'E-Mails außerhalb der Arbeitszeit',
    emailSentimentRisk: 'Kommunikations-Stimmungsrisiko', emailResponseDelay: 'Antwortverzögerung',
  },
  fr: {
    salary: 'Salaire Mensuel', commute: 'Distance de Trajet', satisfaction: 'Score de Satisfaction',
    tenure: "Ancienneté", overTime: 'Heures Supplémentaires', jobInvolvement: 'Implication au Travail',
    emailVolumeDecline: "Baisse du Volume d'E-mails", emailAfterHours: 'E-mails Hors Horaires',
    emailSentimentRisk: 'Risque de Sentiment de Communication', emailResponseDelay: 'Délai de Réponse',
  },
  tr: {
    salary: 'Aylık Maaş', commute: 'İşe Gidiş Mesafesi', satisfaction: 'Memnuniyet Puanı',
    tenure: 'Kıdem', overTime: 'Fazla Mesai', jobInvolvement: 'İşe Bağlılık',
    emailVolumeDecline: 'E-posta Hacminde Düşüş', emailAfterHours: 'Mesai Dışı E-posta',
    emailSentimentRisk: 'İletişim Duygu Riski', emailResponseDelay: 'Yanıt Gecikmesi',
  },
  zh: {
    salary: '月薪', commute: '通勤距离', satisfaction: '满意度评分',
    tenure: '任职年限', overTime: '加班', jobInvolvement: '工作投入度',
    emailVolumeDecline: '邮件量下降', emailAfterHours: '非工作时间发邮件',
    emailSentimentRisk: '沟通情绪风险', emailResponseDelay: '回复延迟',
  },
};

const STRINGS: Record<Lang, Record<string, string>> = {
  en: { nodeStep: 'Decision Node', leafStep: 'Final Prediction', lte: 'is at or below', gt: 'is above',
    trueFlag: 'is flagged', falseFlag: 'is not flagged', movedLeft: 'branch toward lower risk group',
    movedRight: 'branch toward higher risk group', leafOutcome: 'Forest converged on an estimated attrition probability of',
    recImprove: 'Improving', recWouldLower: 'would lower the predicted risk by approximately',
    recNone: 'No single factor stands out — risk is spread across multiple moderate signals.' },
  es: { nodeStep: 'Nodo de Decisión', leafStep: 'Predicción Final', lte: 'es igual o menor que', gt: 'es mayor que',
    trueFlag: 'está marcado', falseFlag: 'no está marcado', movedLeft: 'rama hacia grupo de menor riesgo',
    movedRight: 'rama hacia grupo de mayor riesgo', leafOutcome: 'El modelo estimó una probabilidad de abandono de',
    recImprove: 'Mejorar', recWouldLower: 'reduciría el riesgo estimado en aproximadamente',
    recNone: 'Ningún factor destaca por sí solo: el riesgo se distribuye entre varias señales moderadas.' },
  de: { nodeStep: 'Entscheidungsknoten', leafStep: 'Endgültige Vorhersage', lte: 'liegt bei oder unter', gt: 'liegt über',
    trueFlag: 'ist markiert', falseFlag: 'ist nicht markiert', movedLeft: 'Zweig zu geringerem Risiko',
    movedRight: 'Zweig zu höherem Risiko', leafOutcome: 'Das Modell schätzte eine Fluktuationswahrscheinlichkeit von',
    recImprove: 'Eine Verbesserung von', recWouldLower: 'würde das geschätzte Risiko um etwa senken:',
    recNone: 'Kein einzelner Faktor sticht hervor — das Risiko verteilt sich auf mehrere moderate Signale.' },
  fr: { nodeStep: 'Nœud de Décision', leafStep: 'Prédiction Finale', lte: 'est inférieur ou égal à', gt: 'est supérieur à',
    trueFlag: 'est signalé', falseFlag: "n'est pas signalé", movedLeft: 'branche vers un risque plus faible',
    movedRight: 'branche vers un risque plus élevé', leafOutcome: "Le modèle a estimé une probabilité de départ de",
    recImprove: 'Améliorer', recWouldLower: "réduirait le risque estimé d'environ",
    recNone: "Aucun facteur ne se démarque — le risque est réparti sur plusieurs signaux modérés." },
  tr: { nodeStep: 'Karar Düğümü', leafStep: 'Nihai Tahmin', lte: 'değerine eşit veya altında', gt: 'değerinin üzerinde',
    trueFlag: 'işaretli', falseFlag: 'işaretli değil', movedLeft: 'daha düşük risk grubuna dal',
    movedRight: 'daha yüksek risk grubuna dal', leafOutcome: 'Model tahmini işten ayrılma olasılığını şu şekilde belirledi:',
    recImprove: 'İyileştirmek', recWouldLower: 'tahmini riski yaklaşık şu kadar azaltır:',
    recNone: 'Tek bir faktör öne çıkmıyor — risk birden fazla orta düzey sinyale yayılmış durumda.' },
  zh: { nodeStep: '决策节点', leafStep: '最终预测', lte: '小于或等于', gt: '大于',
    trueFlag: '已标记', falseFlag: '未标记', movedLeft: '分支至较低风险组',
    movedRight: '分支至较高风险组', leafOutcome: '模型预测的离职概率约为',
    recImprove: '改善', recWouldLower: '预计可将风险降低约',
    recNone: '没有单一因素特别突出——风险分散在多个中等信号上。' },
};

const BOOL_FEATURES = new Set<FeatureName>([
  'overTime', 'emailVolumeDecline', 'emailAfterHours', 'emailSentimentRisk', 'emailResponseDelay',
]);

// ---------------------------------------------------------------------------
// Explanation: real tree traversal → decisionPath
// ---------------------------------------------------------------------------

interface DecisionStep {
  step: string;
  condition: string;
  outcome: string;
}

function explainTraversal(x: number[], lang: Lang): DecisionStep[] {
  const s = STRINGS[lang];
  const labels = FEATURE_LABELS[lang];
  const tree = forest.trees[forest.primaryTreeIdx];
  const path: DecisionStep[] = [];
  let node = tree;
  let stepNum = 1;

  while (node.type === 'split') {
    const fName = FEATURE_NAMES[node.featureIdx];
    const label = labels[fName];
    const isBool = BOOL_FEATURES.has(fName);
    const goLeft = x[node.featureIdx] <= node.threshold;

    let condition: string;
    if (isBool) {
      condition = `${label} ${goLeft ? s.falseFlag : s.trueFlag}`;
    } else {
      condition = `${label} ${goLeft ? s.lte : s.gt} ${Math.round(node.threshold * 100) / 100}`;
    }

    path.push({
      step: `${s.nodeStep} ${stepNum}`,
      condition,
      outcome: goLeft ? s.movedLeft : s.movedRight,
    });

    node = goLeft ? node.left : node.right;
    stepNum++;
    if (stepNum > 12) break; // safety cap
  }

  if (node.type === 'leaf') {
    path.push({
      step: s.leafStep,
      condition: `n=${node.n}`,
      outcome: `${s.leafOutcome} ${Math.round(node.prob * 100)}%`,
    });
  }

  return path;
}

// ---------------------------------------------------------------------------
// Recommendations via counterfactual sensitivity analysis against the
// trained forest — perturb one feature toward a healthier value, re-run
// the actual model, and measure the real change in predicted probability.
// ---------------------------------------------------------------------------

function recommend(x: number[], baseProb: number, lang: Lang): string[] {
  const s = STRINGS[lang];
  const labels = FEATURE_LABELS[lang];

  const perturbations: { feature: FeatureName; apply: (v: number[]) => number[] }[] = [
    { feature: 'satisfaction', apply: (v) => { const c = [...v]; c[2] = Math.min(10, c[2] + 3); return c; } },
    { feature: 'jobInvolvement', apply: (v) => { const c = [...v]; c[5] = Math.min(4, c[5] + 1); return c; } },
    { feature: 'overTime', apply: (v) => { const c = [...v]; c[4] = 0; return c; } },
    { feature: 'commute', apply: (v) => { const c = [...v]; c[1] = Math.max(1, c[1] - 10); return c; } },
    { feature: 'emailSentimentRisk', apply: (v) => { const c = [...v]; c[8] = 0; return c; } },
    { feature: 'emailAfterHours', apply: (v) => { const c = [...v]; c[6] = 0; return c; } },
    { feature: 'emailResponseDelay', apply: (v) => { const c = [...v]; c[9] = 0; return c; } },
  ];

  const scored = perturbations
    .map((p) => {
      const newProb = forest.predictProba(p.apply(x));
      const delta = baseProb - newProb;
      return { feature: p.feature, delta };
    })
    .filter((r) => r.delta > 0.005)
    .sort((a, b) => b.delta - a.delta)
    .slice(0, 4);

  if (scored.length === 0) {
    return [s.recNone];
  }

  return scored.map(
    (r) =>
      `${s.recImprove} ${labels[r.feature]} ${s.recWouldLower} ${Math.round(r.delta * 100)}%.`
  );
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

export interface AnalysisResult {
  riskLevel: 'Low' | 'Medium' | 'High';
  riskScore: number;
  decisionPath: DecisionStep[];
  recommendations: string[];
}

export function analyzeAttrition(input: EmployeeFeatures, lang: string): AnalysisResult {
  const validLang: Lang = (['en', 'es', 'de', 'fr', 'tr', 'zh'] as const).includes(lang as Lang)
    ? (lang as Lang)
    : 'en';

  const x = toVector(input);
  const prob = forest.predictProba(x);
  const riskScore = Math.round(prob * 100);
  const riskLevel: 'Low' | 'Medium' | 'High' = riskScore >= 66 ? 'High' : riskScore >= 33 ? 'Medium' : 'Low';

  return {
    riskLevel,
    riskScore,
    decisionPath: explainTraversal(x, validLang),
    recommendations: recommend(x, prob, validLang),
  };
}

// Exposed for a lightweight self-check at server boot (see server.ts).
export function _modelInfo() {
  return { trees: forest.trees.length, maxDepth: MAX_DEPTH, trainingRows: TRAINING_SET_SIZE };
}
