import React, { createContext, useContext, useState, useEffect } from 'react';

export type LanguageCode = 'en' | 'hi' | 'es' | 'de' | 'fr' | 'tr' | 'zh' | 'ar' | 'pt' | 'ja';

export interface Language {
  code: LanguageCode;
  name: string;
  flag: string;
  countryCode: string;
}

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: 'en', name: 'English', flag: '🇬🇧', countryCode: 'gb' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳', countryCode: 'in' },
  { code: 'es', name: 'Español', flag: '🇪🇸', countryCode: 'es' },
  { code: 'de', name: 'Deutsch', flag: '🇩🇪', countryCode: 'de' },
  { code: 'fr', name: 'Français', flag: '🇫🇷', countryCode: 'fr' },
  { code: 'tr', name: 'Türkçe', flag: '🇹🇷', countryCode: 'tr' },
  { code: 'zh', name: '中文', flag: '🇨🇳', countryCode: 'cn' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦', countryCode: 'sa' },
  { code: 'pt', name: 'Português', flag: '🇵🇹', countryCode: 'pt' },
  { code: 'ja', name: '日本語', flag: '🇯🇵', countryCode: 'jp' }
];

export const translations: Record<LanguageCode, Record<string, string>> = {
  en: {
    // Nav & Common
    core_modules: "Core Modules",
    predictive_engine: "Predictive Engine",
    salary_tree: "Salary Tree",
    risk_comparison: "Risk Comparison",
    global_metrics: "Global Metrics",
    access_registry: "Access Registry",
    system_telemetry: "System Telemetry",
    secured: "Secured",
    terminate_session: "Terminate Session",
    workspace_env: "Workspace Environment",
    operator: "Operator",
    administrator: "Administrator",
    guest: "Guest",
    toggle_theme: "Toggle Theme",
    // Login
    nexus_analytics: "Nexus Analytics",
    enterprise_hr: "Enterprise HR Intelligence",
    login: "Log In",
    signup: "Sign Up",
    corp_id: "Corporate Identity",
    access_code: "Password",
    init_session: "Initialize Session",
    reg_identity: "Register Identity",
    secure_conn: "Secure Connection Established",
    admin_access: "Admin Access",
    // Admin Login
    sys_admin: "System Administration",
    secure_core: "Secure Core Access",
    admin_id: "Admin Identifier",
    sec_key: "Password",
    authenticate: "Authenticate",
    reg_admin: "Register Admin",
    std_login: "Standard User Login",
    high_sec_zone: "High Security Zone",
    // Predictive Engine / Analysis View
    predictive_model: "Predictive Model",
    config_profile: "Configure profile parameters to project attrition trajectory.",
    export_csv: "Export CSV",
    subject_profile: "Subject Profile",
    designation: "Designation",
    monthly_comp: "Monthly Compensation",
    satisfaction_idx: "Satisfaction Index",
    transit_dist: "Transit Distance",
    tenure_yrs: "Tenure (Yrs)",
    involvement: "Involvement",
    excess_hours: "Excess Hours Logged",
    execute_projection: "Execute Projection",
    strategic_directives: "Strategic Directives",
    calculated_risk: "Calculated Risk",
    logic_trace: "Logic Trace",
    market_vector: "Market Vector",
    awaiting_seq: "Awaiting Execution Sequence",
    comm_template: "Communication Template",
    ai_generated_outreach: "AI Generated Outreach",
    copy_clipboard: "Copy to Clipboard",
    copied: "Copied!",
    ready_to_send: "Ready to send",
    private_consultation: "Private Consultation Regarding Your Career Path",
    // Risk Levels
    risk_low: "Low",
    risk_medium: "Medium",
    risk_high: "High",
    risk_unknown: "Unknown",
    // Salary Tree
    salary_opt_matrix: "Salary Optimization Matrix",
    corr_tiers: "Decision tree correlating compensation tiers with predicted attrition risk.",
    comp_range: "Compensation Range",
    below_market: "Below Market",
    market_avg: "Market Avg",
    premium: "Premium",
    immediate_review: "Immediate Review",
    monitor_engagement: "Monitor Engagement",
    stable_retention: "Stable Retention",
    // Global Metrics / Stats View
    realtime_metrics: "Real-time metrics on access security and database volume.",
    global_access: "Global Access",
    network_status: "Network Status",
    core_uptime: "Core Uptime",
    hist_attrition: "Historical Attrition Trends",
    satisfaction_risk_corr: "Satisfaction vs Risk Correlation",
    immutable_audit: "Immutable Audit Log",
    identifier: "Identifier",
    unix_ts: "Unix Timestamp",
    integrity: "Integrity",
    valid: "Valid",
    failed: "Failed",
    sync_streams: "Syncing data streams...",
    no_telemetry: "No recorded telemetry.",
    // Access Registry / Users View
    identity_control_plane: "Identity Control Plane",
    master_record: "Master record of all registered identities executing queries.",
    registry_matrix: "Registry Matrix",
    search_principal: "Search principal name...",
    all_clearances: "All Clearances",
    user_principal_name: "User Principal Name",
    auth_utc: "Authentication (UTC)",
    status: "Status",
    clearance: "Clearance",
    actions: "Actions",
    revoke: "Revoke",
    active: "Active",
    revoked: "Revoked",
    handshake: "Establishing handshake...",
    no_identity: "No identity records detected.",
    // Telemetry View
    live_feed: "Live feed of infrastructure events and security audit logs.",
    live_stream: "Live stream",
    export_trail: "Export Log Trail",
    // UI elements
    se_eng: "Software Engineer",
    se_sales: "Sales Executive",
    se_hr: "HR Manager",
    se_rs: "Research Scientist",
    se_da: "Data Analyst",
    change_language: "Change Language",
    init_scenario: "Initialize scenario\nto render data",
    subject: "Subject",
    industry: "Industry",
    dept_avg: "Dept Avg",
    ind_avg: "Ind Avg",
    transit: "Transit"
  },
  es: {
    core_modules: "Módulos Principales",
    predictive_engine: "Motor Predictivo",
    salary_tree: "Árbol de Salarios",
    global_metrics: "Métricas Globales",
    access_registry: "Registro de Acceso",
    system_telemetry: "Telemetría del Sistema",
    secured: "Asegurado",
    terminate_session: "Terminar Sesión",
    workspace_env: "Entorno de Trabajo",
    operator: "Operador",
    administrator: "Administrador",
    guest: "Invitado",
    toggle_theme: "Cambiar Tema",
    nexus_analytics: "Análisis Nexus",
    enterprise_hr: "Inteligencia de RRHH Empresarial",
    login: "Iniciar Sesión",
    signup: "Registrarse",
    corp_id: "Identidad Corporativa",
    access_code: "Contraseña",
    init_session: "Inicializar Sesión",
    reg_identity: "Registrar Identidad",
    secure_conn: "Conexión Segura Establecida",
    admin_access: "Acceso de Administrador",
    sys_admin: "Administración del Sistema",
    secure_core: "Acceso Seguro al Núcleo",
    admin_id: "Identificador de Administrador",
    sec_key: "Contraseña",
    authenticate: "Autenticar",
    reg_admin: "Registrar Administrador",
    std_login: "Inicio de Sesión Estándar",
    high_sec_zone: "Zona de Alta Seguridad",
    predictive_model: "Modelo Predictivo",
    config_profile: "Configure los parámetros del perfil para proyectar la trayectoria de deserción.",
    export_csv: "Exportar CSV",
    subject_profile: "Perfil del Sujeto",
    designation: "Designación",
    monthly_comp: "Compensación Mensual",
    satisfaction_idx: "Índice de Satisfacción",
    transit_dist: "Distancia de Tránsito",
    tenure_yrs: "Antigüedad (Años)",
    involvement: "Involucración",
    excess_hours: "Horas Extras Registradas",
    execute_projection: "Ejecutar Proyección",
    strategic_directives: "Directivas Estratégicas",
    calculated_risk: "Riesgo Calculado",
    logic_trace: "Traza Lógica",
    market_vector: "Vector de Mercado",
    awaiting_seq: "Esperando Secuencia de Ejecución",
    comm_template: "Plantilla de Comunicación",
    ai_generated_outreach: "Contacto Generado por IA",
    copy_clipboard: "Copiar al Portapapeles",
    copied: "¡Copiado!",
    ready_to_send: "Listo para enviar",
    private_consultation: "Consulta privada sobre su trayectoria profesional",
    risk_low: "Bajo",
    risk_medium: "Medio",
    risk_high: "Alto",
    risk_unknown: "Desconocido",
    salary_opt_matrix: "Matriz de Optimización Salarial",
    corr_tiers: "Árbol de decisión que correlaciona los niveles de compensación con el riesgo de deserción previsto.",
    comp_range: "Rango de Compensación",
    below_market: "Bajo el Mercado",
    market_avg: "Promedio del Mercado",
    premium: "Premium",
    immediate_review: "Revisión Inmediata",
    monitor_engagement: "Monitorear Compromiso",
    stable_retention: "Retención Estable",
    realtime_metrics: "Métricas en tiempo real sobre seguridad de acceso y volumen de la base de datos.",
    global_access: "Acceso Global",
    network_status: "Estado de la Red",
    core_uptime: "Tiempo de Actividad",
    hist_attrition: "Tendencias Históricas de Deserción",
    satisfaction_risk_corr: "Correlación entre Satisfacción y Riesgo",
    immutable_audit: "Registro de Auditoría Inmutable",
    identifier: "Identificador",
    unix_ts: "Marca de Tiempo",
    integrity: "Integridad",
    valid: "Válido",
    failed: "Fallido",
    sync_streams: "Sincronizando flujos de datos...",
    no_telemetry: "No hay telemetría registrada.",
    identity_control_plane: "Plano de Control de Identidad",
    master_record: "Registro maestro de todas las identidades registradas que ejecutan consultas.",
    registry_matrix: "Matriz de Registro",
    search_principal: "Buscar nombre principal...",
    all_clearances: "Todas las Autorizaciones",
    user_principal_name: "Nombre Principal del Usuario",
    auth_utc: "Autenticación (UTC)",
    status: "Estado",
    clearance: "Autorización",
    actions: "Acciones",
    revoke: "Revocar",
    active: "Activo",
    revoked: "Revocado",
    handshake: "Estableciendo conexión...",
    no_identity: "No se detectaron registros de identidad.",
    live_feed: "Transmisión en vivo de eventos de infraestructura y registros de auditoría de seguridad.",
    live_stream: "Transmisión en vivo",
    export_trail: "Exportar Registro",
    se_eng: "Ingeniero de Software",
    se_sales: "Ejecutivo de Ventas",
    se_hr: "Gerente de RRHH",
    se_rs: "Científico de Investigación",
    se_da: "Analista de Datos",
    change_language: "Cambiar Idioma",
    init_scenario: "Inicializar escenario\npara renderizar datos",
    subject: "Sujeto",
    industry: "Industria",
    dept_avg: "Prom. Depto",
    ind_avg: "Prom. Ind",
    transit: "Tránsito"
  },
  de: {
    core_modules: "Kernmodule",
    predictive_engine: "Vorhersage-Engine",
    salary_tree: "Gehaltsbaum",
    global_metrics: "Globale Kennzahlen",
    access_registry: "Zugriffsregister",
    system_telemetry: "Systemtelemetrie",
    secured: "Gesichert",
    terminate_session: "Sitzung beenden",
    workspace_env: "Arbeitsumgebung",
    operator: "Bediener",
    administrator: "Administrator",
    guest: "Gast",
    toggle_theme: "Design umschalten",
    nexus_analytics: "Nexus-Analytik",
    enterprise_hr: "Enterprise HR Intelligence",
    login: "Einloggen",
    signup: "Registrieren",
    corp_id: "Unternehmensidentität",
    access_code: "Passwort",
    init_session: "Sitzung starten",
    reg_identity: "Identität registrieren",
    secure_conn: "Sichere Verbindung hergestellt",
    admin_access: "Admin-Zugang",
    sys_admin: "Systemadministration",
    secure_core: "Sicherer Kernzugriff",
    admin_id: "Admin-Kennung",
    sec_key: "Passwort",
    authenticate: "Authentifizieren",
    reg_admin: "Admin registrieren",
    std_login: "Standard-Benutzer-Login",
    high_sec_zone: "Hochsicherheitszone",
    predictive_model: "Prognosemodell",
    config_profile: "Konfigurieren Sie Profilparameter, um die Fluktuationsentwicklung zu prognostizieren.",
    export_csv: "CSV exportieren",
    subject_profile: "Probandenprofil",
    designation: "Bezeichnung",
    monthly_comp: "Monatliche Vergütung",
    satisfaction_idx: "Zufriedenheitsindex",
    transit_dist: "Pendelstrecke",
    tenure_yrs: "Dienstalter (Jahre)",
    involvement: "Engagement",
    excess_hours: "Überstunden erfasst",
    execute_projection: "Prognose ausführen",
    strategic_directives: "Strategische Richtlinien",
    calculated_risk: "Kalkuliertes Risiko",
    logic_trace: "Logik-Trace",
    market_vector: "Marktvektor",
    awaiting_seq: "Warten auf Ausführungssequenz",
    comm_template: "Kommunikationsvorlage",
    ai_generated_outreach: "KI-generierte Ansprache",
    copy_clipboard: "In Zwischenablage kopieren",
    copied: "Kopiert!",
    ready_to_send: "Bereit zum Senden",
    private_consultation: "Private Beratung bezüglich Ihrer Karriereentwicklung",
    risk_low: "Niedrig",
    risk_medium: "Mittel",
    risk_high: "Hoch",
    risk_unknown: "Unbekannt",
    salary_opt_matrix: "Gehaltsoptimierungsmatrix",
    corr_tiers: "Entscheidungsbaum zur Korrelation von Vergütungsstufen mit dem prognostizierten Fluktuationsrisiko.",
    comp_range: "Vergütungsbereich",
    below_market: "Unter Marktwert",
    market_avg: "Marktdurchschnitt",
    premium: "Premium",
    immediate_review: "Sofortige Überprüfung",
    monitor_engagement: "Engagement überwachen",
    stable_retention: "Stabile Bindung",
    realtime_metrics: "Echtzeit-Metriken zur Zugriffssicherheit und zum Datenbankvolumen.",
    global_access: "Globaler Zugriff",
    network_status: "Netzwerkstatus",
    core_uptime: "System-Uhrzeit",
    hist_attrition: "Historische Fluktuationstrends",
    satisfaction_risk_corr: "Korrelation zwischen Zufriedenheit und Risiko",
    immutable_audit: "Unveränderliches Audit-Log",
    identifier: "Kennung",
    unix_ts: "Zeitstempel",
    integrity: "Integrität",
    valid: "Gültig",
    failed: "Fehlgeschlagen",
    sync_streams: "Datenströme werden synchronisiert...",
    no_telemetry: "Keine Telemetriedaten erfasst.",
    identity_control_plane: "Identitätskontrollzentrum",
    master_record: "Stammsatz aller registrierten Identitäten, die Abfragen ausführen.",
    registry_matrix: "Registrierungsmatrix",
    search_principal: "Prinzipalname suchen...",
    all_clearances: "Alle Freigaben",
    user_principal_name: "Benutzer-Prinzipalname",
    auth_utc: "Authentifizierung (UTC)",
    status: "Status",
    clearance: "Freigabestufe",
    actions: "Aktionen",
    revoke: "Widerrufen",
    active: "Aktiv",
    revoked: "Widerrufen",
    handshake: "Verbindung wird hergestellt...",
    no_identity: "Keine Identitätsdaten gefunden.",
    live_feed: "Live-Feed von Infrastrukturereignissen und Sicherheitsaudit-Logs.",
    live_stream: "Live-Stream",
    export_trail: "Protokoll exportieren",
    se_eng: "Software-Entwickler",
    se_sales: "Vertriebsmitarbeiter",
    se_hr: "HR Manager",
    se_rs: "Forschungswissenschaftler",
    se_da: "Datenanalyst",
    change_language: "Sprache wechseln",
    init_scenario: "Szenario initialisieren,\num Daten anzuzeigen",
    subject: "Proband",
    industry: "Branche",
    dept_avg: "Abt.-Schnitt",
    ind_avg: "Branchen-Schnitt",
    transit: "Anfahrt"
  },
  fr: {
    core_modules: "Modules Principaux",
    predictive_engine: "Moteur Prédictif",
    salary_tree: "Arbre des Salaires",
    global_metrics: "Métriques Globales",
    access_registry: "Registre d'Accès",
    system_telemetry: "Télémétrie Système",
    secured: "Sécurisé",
    terminate_session: "Terminer la Session",
    workspace_env: "Environnement de Travail",
    operator: "Opérateur",
    administrator: "Administrateur",
    guest: "Invité",
    toggle_theme: "Changer de Thème",
    nexus_analytics: "Analyse Nexus",
    enterprise_hr: "Intelligence RH d'Entreprise",
    login: "Connexion",
    signup: "S'inscrire",
    corp_id: "Identité d'Entreprise",
    access_code: "Mot de passe",
    init_session: "Initialiser la Session",
    reg_identity: "Enregistrer l'Identité",
    secure_conn: "Connexion Sécurisée Établie",
    admin_access: "Accès Administrateur",
    sys_admin: "Administration Système",
    secure_core: "Accès Noyau Sécurisé",
    admin_id: "Identifiant Administrateur",
    sec_key: "Mot de passe",
    authenticate: "S'authentifier",
    reg_admin: "Enregistrer l'Admin",
    std_login: "Connexion Utilisateur Standard",
    high_sec_zone: "Zone de Haute Sécurité",
    predictive_model: "Modèle Prédictif",
    config_profile: "Configurez les paramètres du profil pour projeter la trajectoire d'attrition.",
    export_csv: "Exporter en CSV",
    subject_profile: "Profil du Sujet",
    designation: "Désignation",
    monthly_comp: "Rémunération Mensuelle",
    satisfaction_idx: "Indice de Satisfaction",
    transit_dist: "Distance de Transport",
    tenure_yrs: "Ancienneté (Années)",
    involvement: "Implication",
    excess_hours: "Heures Supplémentaires Enregistrées",
    execute_projection: "Exécuter la Projection",
    strategic_directives: "Directives Stratégiques",
    calculated_risk: "Risque Calculé",
    logic_trace: "Trace Logique",
    market_vector: "Vecteur de Marché",
    awaiting_seq: "En attente de la séquence d'exécution",
    comm_template: "Modèle de Communication",
    ai_generated_outreach: "Sensibilisation générée par IA",
    copy_clipboard: "Copier dans le Presse-papiers",
    copied: "Copié !",
    ready_to_send: "Prêt à envoyer",
    private_consultation: "Consultation privée concernant votre parcours professionnel",
    risk_low: "Faible",
    risk_medium: "Moyen",
    risk_high: "Élevé",
    risk_unknown: "Inconnu",
    salary_opt_matrix: "Matrice d'Optimisation des Salaires",
    corr_tiers: "Arbre de décision corrélant les niveaux de rémunération avec le risque d'attrition prévu.",
    comp_range: "Plage de Rémunération",
    below_market: "En dessous du Marché",
    market_avg: "Moyenne du Marché",
    premium: "Premium",
    immediate_review: "Révision Immédiate",
    monitor_engagement: "Surveiller l'Engagement",
    stable_retention: "Rétention Stable",
    realtime_metrics: "Métriques en temps réel sur la sécurité des accès et le volume de la base de données.",
    global_access: "Accès Global",
    network_status: "État du Réseau",
    core_uptime: "Temps d'activité",
    hist_attrition: "Tendances Historiques d'Attrition",
    satisfaction_risk_corr: "Corrélation Satisfaction vs Risque",
    immutable_audit: "Journal d'Audit Immuable",
    identifier: "Identifiant",
    unix_ts: "Horodatage",
    integrity: "Integrité",
    valid: "Valide",
    failed: "Échoué",
    sync_streams: "Synchronisation des flux de données...",
    no_telemetry: "Aucune télémétrie enregistrée.",
    identity_control_plane: "Plan de Contrôle des Identités",
    master_record: "Registre maître de toutes les identités enregistrées exécutant des requêtes.",
    registry_matrix: "Matrice de Registre",
    search_principal: "Rechercher un nom principal...",
    all_clearances: "Toutes les Autorisations",
    user_principal_name: "Nom Principal de l'Utilisateur",
    auth_utc: "Authentification (UTC)",
    status: "Statut",
    clearance: "Autorisation",
    actions: "Actions",
    revoke: "Révoquer",
    active: "Actif",
    revoked: "Révoqué",
    handshake: "Établissement de la connexion...",
    no_identity: "Aucun enregistrement d'identité détecté.",
    live_feed: "Flux en direct des événements d'infrastructure et des journaux d'audit de sécurité.",
    live_stream: "Flux en direct",
    export_trail: "Exporter le registre",
    se_eng: "Ingénieur Logiciel",
    se_sales: "Responsable des Ventes",
    se_hr: "Gestionnaire des RH",
    se_rs: "Chercheur Scientifique",
    se_da: "Analyste de Données",
    change_language: "Changer de langue",
    init_scenario: "Initialiser le scénario\npour afficher les données",
    subject: "Sujet",
    industry: "Secteur",
    dept_avg: "Moy. Dépt",
    ind_avg: "Moy. Secteur",
    transit: "Transport"
  },
  tr: {
    core_modules: "Temel Modüller",
    predictive_engine: "Tahmin Motoru",
    salary_tree: "Maaş Ağacı",
    global_metrics: "Küresel Metrikler",
    access_registry: "Erişim Kaydı",
    system_telemetry: "Sistem Telemetrisi",
    secured: "Güvenli",
    terminate_session: "Oturumu Sonlandır",
    workspace_env: "Çalışma Alanı Ortamı",
    operator: "Operatör",
    administrator: "Yönetici",
    guest: "Misafir",
    toggle_theme: "Temayı Değiştir",
    nexus_analytics: "Nexus Analitiği",
    enterprise_hr: "Kurumsal İK Zekası",
    login: "Giriş Yap",
    signup: "Kayıt Ol",
    corp_id: "Kurumsal Kimlik",
    access_code: "Şifre",
    init_session: "Oturumu Başlat",
    reg_identity: "Kimliği Kaydet",
    secure_conn: "Güvenli Bağlantı Sağlandı",
    admin_access: "Yönetici Erişimi",
    sys_admin: "Sistem Yönetimi",
    secure_core: "Güvenli Çekirdek Erişimi",
    admin_id: "Yönetici Kimliği",
    sec_key: "Şifre",
    authenticate: "Kimlik Doğrula",
    reg_admin: "Yönetici Kaydet",
    std_login: "Standart Kullanıcı Girişi",
    high_sec_zone: "Yüksek Güvenlikli Bölge",
    predictive_model: "Tahmin Modeli",
    config_profile: "Yıpranma yörüngesini tahmin etmek için profil parametrelerini yapılandırın.",
    export_csv: "CSV Dışa Aktar",
    subject_profile: "Çalışan Profili",
    designation: "Unvan",
    monthly_comp: "Aylık Gelir",
    satisfaction_idx: "Memnuniyet Endeksi",
    transit_dist: "Ulaşım Mesafesi",
    tenure_yrs: "Deneyim (Yıl)",
    involvement: "Katılım",
    excess_hours: "Fazla Mesai Saati",
    execute_projection: "Projeksiyonu Çalıştır",
    strategic_directives: "Stratejik Yönergeler",
    calculated_risk: "Hesaplanan Risk",
    logic_trace: "Mantık İzleyici",
    market_vector: "Piyasa Vektörü",
    awaiting_seq: "Yürütme Dizisi Bekleniyor",
    comm_template: "İletişim Şablonu",
    ai_generated_outreach: "Yapay Zeka Destekli Ulaşım",
    copy_clipboard: "Panoya Kopyala",
    copied: "Kopyalandı!",
    ready_to_send: "Gönderime hazır",
    private_consultation: "Kariyer Yolunuz Hakkında Özel Görüşme",
    risk_low: "Düşük",
    risk_medium: "Orta",
    risk_high: "Yüksek",
    risk_unknown: "Bilinmiyor",
    salary_opt_matrix: "Maaş Optimizasyon Matrisi",
    corr_tiers: "Gelir kademelerini tahmin edilen yıpranma riski ile ilişkilendiren karar ağacı.",
    comp_range: "Maaş Aralığı",
    below_market: "Piyasa Altı",
    market_avg: "Piyasa Ortalaması",
    premium: "Premium",
    immediate_review: "Acil İnceleme",
    monitor_engagement: "Katılımı İzle",
    stable_retention: "Kararlı Elde Tutma",
    realtime_metrics: "Erişim güvenliği ve veritabanı hacmine ilişkin gerçek zamanlı metrikler.",
    global_access: "Genel Erişim",
    network_status: "Ağ Durumu",
    core_uptime: "Çalışma Süresi",
    hist_attrition: "Tarihsel Yıpranma Eğilimleri",
    satisfaction_risk_corr: "Memnuniyet ve Risk İlişkisi",
    immutable_audit: "Değiştirilemez Denetim Günlüğü",
    identifier: "Kimlik Tanımlayıcı",
    unix_ts: "Zaman Damgası",
    integrity: "Bütünlük",
    valid: "Geçerli",
    failed: "Başarısız",
    sync_streams: "Veri akışları senkronize ediliyor...",
    no_telemetry: "Kayıtlı telemetri bulunmuyor.",
    identity_control_plane: "Kimlik Kontrol Paneli",
    master_record: "Sorguları yürüten tüm kayıtlı kimliklerin ana kaydı.",
    registry_matrix: "Kayıt Matrisi",
    search_principal: "Çalışan adı ara...",
    all_clearances: "Tüm Yetkiler",
    user_principal_name: "Kullanıcı Kimliği Adı",
    auth_utc: "Kimlik Doğrulama (UTC)",
    status: "Durum",
    clearance: "Erişim Yetkisi",
    actions: "İşlemler",
    revoke: "Yetkiyi Kaldır",
    active: "Etkin",
    revoked: "İptal Edildi",
    handshake: "Bağlantı kuruluyor...",
    no_identity: "Kimlik kaydı bulunamadı.",
    live_feed: "Altyapı olayları ve güvenlik denetim günlüklerinin canlı akışı.",
    live_stream: "Canlı Yayın",
    export_trail: "Günlüğü Dışa Aktar",
    se_eng: "Yazılım Mühendisi",
    se_sales: "Satış Temsilcisi",
    se_hr: "İK Yöneticisi",
    se_rs: "Araştırma Görevlisi",
    se_da: "Veri Analisti",
    change_language: "Dil Değiştir",
    init_scenario: "Verileri işlemek için\nsenaryoyu başlatın",
    subject: "Çalışan",
    industry: "Sektör",
    dept_avg: "Dep. Ort.",
    ind_avg: "Sektör Ort.",
    transit: "Ulaşım"
  },
  zh: {
    core_modules: "核心模块",
    predictive_engine: "预测引擎",
    salary_tree: "薪酬树",
    global_metrics: "全局指标",
    access_registry: "访问注册",
    system_telemetry: "系统遥测",
    secured: "安全",
    terminate_session: "终止会话",
    workspace_env: "工作空间环境",
    operator: "操作员",
    administrator: "管理员",
    guest: "访客",
    toggle_theme: "切换主题",
    nexus_analytics: "Nexus 数据分析",
    enterprise_hr: "企业人力资源智能",
    login: "登录",
    signup: "注册",
    corp_id: "企业身份",
    access_code: "密码",
    init_session: "初始化会话",
    reg_identity: "注册身份",
    secure_conn: "已建立安全连接",
    admin_access: "管理员访问",
    sys_admin: "系统管理",
    secure_core: "安全核心访问",
    admin_id: "管理员标识",
    sec_key: "密码",
    authenticate: "身份验证",
    reg_admin: "注册管理员",
    std_login: "普通用户登录",
    high_sec_zone: "高安全区域",
    predictive_model: "预测模型",
    config_profile: "配置档案参数以预测流失轨迹。",
    export_csv: "导出 CSV",
    subject_profile: "对象档案",
    designation: "职位",
    monthly_comp: "月度薪酬",
    satisfaction_idx: "满意度指数",
    transit_dist: "通勤距离",
    tenure_yrs: "任期 (年)",
    involvement: "工作投入度",
    excess_hours: "记录加班时间",
    execute_projection: "执行预测",
    strategic_directives: "战略方针",
    calculated_risk: "计算风险",
    logic_trace: "逻辑追踪",
    market_vector: "市场特征",
    awaiting_seq: "等待执行序列",
    comm_template: "沟通模板",
    ai_generated_outreach: "AI 生成的沟通邮件",
    copy_clipboard: "复制到剪贴板",
    copied: "已复制！",
    ready_to_send: "准备发送",
    private_consultation: "关于您职业发展路径的私密咨询",
    risk_low: "低",
    risk_medium: "中",
    risk_high: "高",
    risk_unknown: "未知",
    salary_opt_matrix: "薪酬优化矩阵",
    corr_tiers: "将薪酬等级与预测流失风险关联的决策树。",
    comp_range: "薪酬范围",
    below_market: "低于市场水平",
    market_avg: "市场平均水平",
    premium: "溢价",
    immediate_review: "立即评估",
    monitor_engagement: "监控参与度",
    stable_retention: "稳定保留",
    realtime_metrics: "关于访问安全和数据库容量的实时指标。",
    global_access: "全局访问",
    network_status: "网络状态",
    core_uptime: "核心运行时间",
    hist_attrition: "历史流失率趋势",
    satisfaction_risk_corr: "满意度与风险相关性",
    immutable_audit: "不可变审计日志",
    identifier: "标识符",
    unix_ts: "时间戳",
    integrity: "完整性",
    valid: "有效",
    failed: "失败",
    sync_streams: "正在同步数据流...",
    no_telemetry: "无遥测记录。",
    identity_control_plane: "身份控制平面",
    master_record: "执行查询的所有已注册身份的主记录。",
    registry_matrix: "注册矩阵",
    search_principal: "搜索主体名称...",
    all_clearances: "所有权限等级",
    user_principal_name: "用户主体名称",
    auth_utc: "身份验证 (UTC)",
    status: "状态",
    clearance: "权限等级",
    actions: "操作",
    revoke: "撤销",
    active: "活跃",
    revoked: "已撤销",
    handshake: "正在建立连接...",
    no_identity: "未检测到身份记录。",
    live_feed: "基础架构事件和安全审计日志的实时馈送。",
    live_stream: "实时流",
    export_trail: "导出日志轨迹",
    se_eng: "软件工程师",
    se_sales: "销售主管",
    se_hr: "人力资源经理",
    se_rs: "研发科学家",
    se_da: "数据分析师",
    change_language: "切换语言",
    init_scenario: "初始化场景以渲染数据",
    subject: "对象",
    industry: "行业",
    dept_avg: "部门平均",
    ind_avg: "行业平均",
    transit: "通勤"
  },
  hi: {
    core_modules: "मुख्य मॉड्यूल",
    predictive_engine: "भविष्यवाणी इंजन",
    salary_tree: "वेतन ट्री",
    global_metrics: "वैश्विक मेट्रिक्स",
    access_registry: "पहुंच रजिस्ट्री",
    system_telemetry: "सिस्टम टेलीमेट्री",
    secured: "सुरक्षित",
    terminate_session: "सत्र समाप्त करें",
    workspace_env: "कार्यक्षेत्र वातावरण",
    operator: "ऑपरेटर",
    administrator: "प्रशासक",
    guest: "अतिथि",
    toggle_theme: "थीम बदलें",
    nexus_analytics: "नेक्सस एनालिटिक्स",
    enterprise_hr: "एंटरप्राइज एचआर इंटेलिजेंस",
    login: "लॉग इन करें",
    signup: "साइन अप करें",
    corp_id: "कॉरपोरेट पहचान",
    access_code: "पासवर्ड",
    init_session: "सत्र प्रारंभ करें",
    reg_identity: "पहचान पंजीकृत करें",
    secure_conn: "सुरक्षित कनेक्शन स्थापित",
    admin_access: "प्रशासक पहुंच",
    sys_admin: "सिस्टम प्रशासन",
    secure_core: "सुरक्षित कोर एक्सेस",
    admin_id: "प्रशासक पहचानकर्ता",
    sec_key: "पासवर्ड",
    authenticate: "प्रमाणित करें",
    reg_admin: "प्रशासक पंजीकृत करें",
    std_login: "मानक उपयोगकर्ता लॉगिन",
    high_sec_zone: "उच्च सुरक्षा क्षेत्र",
    predictive_model: "भविष्यवाणी मॉडल",
    config_profile: "कर्मचारी के जाने के पथ का अनुमान लगाने के लिए प्रोफ़ाइल पैरामीटर कॉन्फ़िगर करें।",
    export_csv: "सीएसवी निर्यात करें",
    subject_profile: "विषय प्रोफ़ाइल",
    designation: "पद",
    monthly_comp: "मासिक मुआवजा",
    satisfaction_idx: "संतुष्टि सूचकांक",
    transit_dist: "यात्रा दूरी",
    tenure_yrs: "कार्यकाल (वर्ष)",
    involvement: "भागीदारी",
    excess_hours: "अतिरिक्त घंटे दर्ज किए गए",
    execute_projection: "अनुमान निष्पादित करें",
    strategic_directives: "रणनीतिक निर्देश",
    calculated_risk: "परिकलित जोखिम",
    logic_trace: "तर्क ट्रेस",
    market_vector: "बाजार वेक्टर",
    awaiting_seq: "निष्पादन अनुक्रम की प्रतीक्षा है",
    comm_template: "संचार टेम्पलेट",
    ai_generated_outreach: "एआई द्वारा जनरेट किया गया आउटरीच",
    copy_clipboard: "क्लिपबोर्ड पर कॉपी करें",
    copied: "कॉपी किया गया!",
    ready_to_send: "भेजने के लिए तैयार",
    private_consultation: "आपके करियर पथ के संबंध में निजी परामर्श",
    risk_low: "कम",
    risk_medium: "मध्यम",
    risk_high: "उच्च",
    risk_unknown: "अअज्ञात",
    salary_opt_matrix: "वेतन अनुकूलन मैट्रिक्स",
    corr_tiers: "मुनावजा स्तरों और अनुमानित नौकरी छोड़ने के जोखिम के बीच संबंध दर्शाने वाला डिसीजन ट्री।",
    comp_range: "मुआवजा सीमा",
    below_market: "बाजार से नीचे",
    market_avg: "बाजार औसत",
    premium: "प्रीमियम",
    immediate_review: "तत्काल समीक्षा",
    monitor_engagement: "सगाई की निगरानी करें",
    stable_retention: "स्थिर प्रतिधारण",
    realtime_metrics: "पहुंच सुरक्षा और डेटाबेस वॉल्यूम पर वास्तविक समय के मेट्रिक्स।",
    global_access: "वैश्विक पहुंच",
    network_status: "नेटवर्क स्थिति",
    core_uptime: "कोर अपटाइम",
    hist_attrition: "ऐतिहासिक नौकरी छोड़ने की प्रवृत्तियाँ",
    satisfaction_risk_corr: "संतुष्टि बनाम जोखिम सहसंबंध",
    immutable_audit: "अपरिवर्तनीय ऑडिट लॉग",
    identifier: "पहचानकर्ता",
    unix_ts: "यूनिक्स टाइमस्टैम्प",
    integrity: "अखंडता",
    valid: "वैध",
    failed: "विफल",
    sync_streams: "डेटा स्ट्रीम सिंक की जा रही हैं...",
    no_telemetry: "कोई टेलीमेट्री रिकॉर्ड नहीं मिली।",
    identity_control_plane: "पहचान नियंत्रण तल",
    master_record: "क्वेरी निष्पादित करने वाले सभी पंजीकृत पहचानों का मास्टर रिकॉर्ड।",
    registry_matrix: "रजिस्ट्री मैट्रिक्स",
    search_principal: "प्रमुख नाम खोजें...",
    all_clearances: "सभी अनुमतियाँ",
    user_principal_name: "उपयोगकर्ता प्रमुख नाम",
    auth_utc: "प्रमाणीकरण (UTC)",
    status: "स्थिति",
    clearance: "अनुमति",
    actions: "कार्रवाई",
    revoke: "रद्द करें",
    active: "सक्रिय",
    revoked: "रद्द",
    handshake: "हैंडशेक स्थापित किया जा रहा है...",
    no_identity: "कोई पहचान रिकॉर्ड नहीं मिला।",
    live_feed: "इन्फ्रास्ट्रक्चर घटनाओं और सुरक्षा ऑडिट लॉग का लाइव फीड।",
    live_stream: "लाइव स्ट्रीम",
    export_trail: "लॉग ट्रेल निर्यात करें",
    se_eng: "सॉफ्टवेयर इंजीनियर",
    se_sales: "बिक्री कार्यकारी",
    se_hr: "मानव संसाधन प्रबंधक",
    se_rs: "अनुसंधान वैज्ञानिक",
    se_da: "डेटा विश्लेषक",
    change_language: "भाषा बदलें",
    init_scenario: "डेटा प्रस्तुत करने के लिए\nपरिदृश्य प्रारंभ करें",
    subject: "विषय",
    industry: "उद्योग",
    dept_avg: "विभाग औसत",
    ind_avg: "उद्योग औसत",
    transit: "यात्रा"
  },
  ar: {
    core_modules: "الوحدات الأساسية",
    predictive_engine: "محرك التنبؤ",
    salary_tree: "شجرة الرواتب",
    global_metrics: "المقاييس العالمية",
    access_registry: "سجل الوصول",
    system_telemetry: "قياس تتبع النظام",
    secured: "مؤمن",
    terminate_session: "إنهاء الجلسة",
    workspace_env: "بيئة العمل",
    operator: "مشغل",
    administrator: "مسؤول",
    guest: "ضيف",
    toggle_theme: "تبديل المظهر",
    nexus_analytics: "تحليلات نيكسس",
    enterprise_hr: "ذكاء الموارد البشرية للمؤسسات",
    login: "تسجيل الدخول",
    signup: "تسجيل جديد",
    corp_id: "الهوية المؤسسية",
    access_code: "كلمة المرور",
    init_session: "بدء الجلسة",
    reg_identity: "تسجيل الهوية",
    secure_conn: "تم إنشاء اتصال آمن",
    admin_access: "وصول المسؤول",
    sys_admin: "إدارة النظام",
    secure_core: "وصول آمن للنواة",
    admin_id: "معرف المسؤول",
    sec_key: "كلمة المرور",
    authenticate: "تأكيد الهوية",
    reg_admin: "تسجيل مسؤول",
    std_login: "تسجيل دخول مستخدم عادي",
    high_sec_zone: "منطقة أمان عالية",
    predictive_model: "النموذج التنبؤي",
    config_profile: "تكوين معلمات الملف الشخصي لعرض مسار ترك العمل المتوقع.",
    export_csv: "تصدير CSV",
    subject_profile: "ملف تعريف الموظف",
    designation: "المسمى الوظيفي",
    monthly_comp: "التعويض الشهري",
    satisfaction_idx: "مؤشر الرضا",
    transit_dist: "مسافة التنقل",
    tenure_yrs: "مدة الخدمة (سنوات)",
    involvement: "المشاركة الوظيفية",
    excess_hours: "ساعات العمل الإضافية المسجلة",
    execute_projection: "تنفيذ التنبؤ",
    strategic_directives: "التوجيهات الإستراتيجية",
    calculated_risk: "المخاطر المحسوبة",
    logic_trace: "تتبع المنطق",
    market_vector: "متجه السوق",
    awaiting_seq: "في انتظار بدء التنفيذ",
    comm_template: "نموذج الاتصال",
    ai_generated_outreach: "التواصل المولد بواسطة الذكاء الاصطناعي",
    copy_clipboard: "نسخ إلى الحافظة",
    copied: "تم النسخ!",
    ready_to_send: "جاهز للإرسال",
    private_consultation: "استشارة خاصة بخصوص مسارك المهني",
    risk_low: "منخفض",
    risk_medium: "متوسط",
    risk_high: "مرتفع",
    risk_unknown: "غير معروف",
    salary_opt_matrix: "مصفوفة تحسين الرواتب",
    corr_tiers: "شجرة القرار التي تربط مستويات التعويض بمخاطر ترك العمل المتوقعة.",
    comp_range: "نطاق التعويض",
    below_market: "أقل من سعر السوق",
    market_avg: "متوسط السوق",
    premium: "متميز (بريميوم)",
    immediate_review: "مراجعة فورية",
    monitor_engagement: "مراقبة التفاعل",
    stable_retention: "احتفاظ مستقر",
    realtime_metrics: "مقاييس في الوقت الفعلي لأمان الوصول وحجم قاعدة البيانات.",
    global_access: "الوصول العالمي",
    network_status: "حالة الشبكة",
    core_uptime: "وقت تشغيل النواة",
    hist_attrition: "اتجاهات ترك العمل التاريخية",
    satisfaction_risk_corr: "الارتباط بين الرضا والمخاطر",
    immutable_audit: "سجل تدقيق غير قابل للتغيير",
    identifier: "المعرف",
    unix_ts: "طابع زمني يونكس",
    integrity: "السلامة",
    valid: "صالح",
    failed: "فاشل",
    sync_streams: "جاري مزامنة تدفق البيانات...",
    no_telemetry: "لا يوجد بيانات تتبع مسجلة.",
    identity_control_plane: "مستوى التحكم بالهوية",
    master_record: "السجل الرئيسي لجميع الهويات المسجلة التي تنفذ استعلامات.",
    registry_matrix: "مصفوفة السجل",
    search_principal: "البحث عن الاسم الأساسي...",
    all_clearances: "جميع التصاريح",
    user_principal_name: "اسم المستخدم الأساسي",
    auth_utc: "المصادقة (UTC)",
    status: "الحالة",
    clearance: "التصريح الأمني",
    actions: "الإجراءات",
    revoke: "إلغاء",
    active: "نشط",
    revoked: "ملغى",
    handshake: "جاري إنشاء المصافحة...",
    no_identity: "لم يتم العثور على سجلات هوية.",
    live_feed: "بث مباشر لأحداث البنية التحتية وسجلات تدقيق الأمان.",
    live_stream: "بث مباشر",
    export_trail: "تصدير مسار السجل",
    se_eng: "مهندس برمجيات",
    se_sales: "تنفيذي مبيعات",
    se_hr: "مدير الموارد البشرية",
    se_rs: "عالم أبحاث",
    se_da: "محلل بيانات",
    change_language: "تغيير اللغة",
    init_scenario: "ابدأ السيناريو لعرض البيانات",
    subject: "الموظف",
    industry: "القطاع",
    dept_avg: "متوسط القسم",
    ind_avg: "متوسط القطاع",
    transit: "التنقل"
  },
  pt: {
    core_modules: "Módulos Principais",
    predictive_engine: "Motor Preditivo",
    salary_tree: "Árvore Salarial",
    global_metrics: "Métricas Globais",
    access_registry: "Registro de Acessos",
    system_telemetry: "Telemetria do Sistema",
    secured: "Protegido",
    terminate_session: "Encerrar Sessão",
    workspace_env: "Ambiente de Trabalho",
    operator: "Operador",
    administrator: "Administrador",
    guest: "Convidado",
    toggle_theme: "Alternar Tema",
    nexus_analytics: "Análise Nexus",
    enterprise_hr: "Inteligência Corporativa de RH",
    login: "Entrar",
    signup: "Cadastrar",
    corp_id: "Identidade Corporativa",
    access_code: "Senha",
    init_session: "Iniciar Sessão",
    reg_identity: "Registrar Identidade",
    secure_conn: "Conexão Segura Estabelecida",
    admin_access: "Acesso Administrador",
    sys_admin: "Administração do Sistema",
    secure_core: "Acesso Seguro ao Núcleo",
    admin_id: "Identificador do Administrador",
    sec_key: "Senha",
    authenticate: "Autenticar",
    reg_admin: "Registrar Administrador",
    std_login: "Login de Usuário Padrão",
    high_sec_zone: "Zona de Alta Segurança",
    predictive_model: "Modelo Preditivo",
    config_profile: "Configure os parâmetros do perfil para projetar a trajetória de rotatividade.",
    export_csv: "Exportar CSV",
    subject_profile: "Perfil do Funcionário",
    designation: "Cargo",
    monthly_comp: "Remuneração Mensal",
    satisfaction_idx: "Índice de Satisfação",
    transit_dist: "Distância de Deslocamento",
    tenure_yrs: "Tempo de Empresa (Anos)",
    involvement: "Envolvimento no Trabalho",
    excess_hours: "Horas Extras Registradas",
    execute_projection: "Executar Projeção",
    strategic_directives: "Diretrizes Estratégicas",
    calculated_risk: "Risco Calculado",
    logic_trace: "Rastreamento Lógico",
    market_vector: "Vetor de Mercado",
    awaiting_seq: "Aguardando Execução",
    comm_template: "Modelo de Comunicação",
    ai_generated_outreach: "Mensagem Gerada por IA",
    copy_clipboard: "Copiar para a Área de Transferência",
    copied: "Copiado!",
    ready_to_send: "Pronto para enviar",
    private_consultation: "Consulta privada sobre sua trajetória profissional",
    risk_low: "Baixo",
    risk_medium: "Médio",
    risk_high: "Alto",
    risk_unknown: "Desconhecido",
    salary_opt_matrix: "Matriz de Otimização Salarial",
    corr_tiers: "Árvore de decisão que correlaciona faixas de remuneração com risco de rotatividade previsto.",
    comp_range: "Faixa de Remuneração",
    below_market: "Abaixo do Mercado",
    market_avg: "Média do Mercado",
    premium: "Premium",
    immediate_review: "Revisão Imediata",
    monitor_engagement: "Monitorar Engajamento",
    stable_retention: "Retenção Estável",
    realtime_metrics: "Métricas em tempo real sobre segurança de acessos e volume de banco de dados.",
    global_access: "Acesso Global",
    network_status: "Status da Rede",
    core_uptime: "Uptime do Sistema",
    hist_attrition: "Tendências Históricas de Rotatividade",
    satisfaction_risk_corr: "Correlação de Satisfação vs Risco",
    immutable_audit: "Log de Auditoria Imutável",
    identifier: "Identificador",
    unix_ts: "Timestamp Unix",
    integrity: "Integridade",
    valid: "Válido",
    failed: "Falhou",
    sync_streams: "Sincronizando fluxo de dados...",
    no_telemetry: "Nenhuma telemetria registrada.",
    identity_control_plane: "Plano de Controle de Identidade",
    master_record: "Registro mestre de todas as identidades cadastradas executando consultas.",
    registry_matrix: "Matriz de Registro",
    search_principal: "Buscar nome principal...",
    all_clearances: "Todas as Permissões",
    user_principal_name: "Nome Principal do Usuário",
    auth_utc: "Autenticação (UTC)",
    status: "Status",
    clearance: "Nível de Permissão",
    actions: "Ações",
    revoke: "Revogar",
    active: "Ativo",
    revoked: "Revogado",
    handshake: "Estabelecendo comunicação...",
    no_identity: "Nenhum registro de identidade detectado.",
    live_feed: "Fluxo ao vivo de eventos de infraestrutura e logs de auditoria de segurança.",
    live_stream: "Fluxo ao vivo",
    export_trail: "Exportar Histórico de Logs",
    se_eng: "Engenheiro de Software",
    se_sales: "Executivo de Vendas",
    se_hr: "Gerente de RH",
    se_rs: "Cientista de Pesquisa",
    se_da: "Analista de Dados",
    change_language: "Mudar Idioma",
    init_scenario: "Inicializar cenário\npara renderizar dados",
    subject: "Funcionário",
    industry: "Setor",
    dept_avg: "Média do Dept",
    ind_avg: "Média do Setor",
    transit: "Deslocamento"
  },
  ja: {
    core_modules: "コアモジュール",
    predictive_engine: "予測エンジン",
    salary_tree: "給与決定ツリー",
    global_metrics: "グローバル指標",
    access_registry: "アクセス登録簿",
    system_telemetry: "システムテレメトリ",
    secured: "セキュア保護済",
    terminate_session: "セッション終了",
    workspace_env: "ワークスペース環境",
    operator: "オペレーター",
    administrator: "管理者",
    guest: "ゲスト",
    toggle_theme: "テーマ切替",
    nexus_analytics: "Nexus アナリティクス",
    enterprise_hr: "エンタープライズ人事インテリジェンス",
    login: "ログイン",
    signup: "新規登録",
    corp_id: "企業ID",
    access_code: "パスワード",
    init_session: "セッション開始",
    reg_identity: "ID 登録",
    secure_conn: "セキュア接続確立",
    admin_access: "管理者アクセス",
    sys_admin: "システム管理",
    secure_core: "セキュアコアアクセス",
    admin_id: "管理者識別子",
    sec_key: "パスワード",
    authenticate: "認証",
    reg_admin: "管理者登録",
    std_login: "標準ユーザーログイン",
    high_sec_zone: "高セキュリティゾーン",
    predictive_model: "予測モデル",
    config_profile: "離職予測をプロットするための各種パラメータ設定",
    export_csv: "CSV出力",
    subject_profile: "対象者プロフィール",
    designation: "役職",
    monthly_comp: "月額基本給",
    satisfaction_idx: "仕事満足度",
    transit_dist: "通勤距離",
    tenure_yrs: "在籍年数",
    involvement: "仕事への関与度",
    excess_hours: "時間外勤務実績あり",
    execute_projection: "予測実行",
    strategic_directives: "戦略的ディレクティブ",
    calculated_risk: "算出されたリスク",
    logic_trace: "ロジックトレース",
    market_vector: "市場ベクトル",
    awaiting_seq: "実行待ち...",
    comm_template: "連絡文面テンプレート",
    ai_generated_outreach: "AI 生成アウトリーチ文面",
    copy_clipboard: "クリップボードにコピー",
    copied: "コピーしました！",
    ready_to_send: "送信準備完了",
    private_consultation: "キャリアパスに関する個別相談について",
    risk_low: "低",
    risk_medium: "中",
    risk_high: "高",
    risk_unknown: "不明",
    salary_opt_matrix: "給与最適化マトリクス",
    corr_tiers: "報酬レベルと離職予測リスクをマッピングした意思決定ツリー",
    comp_range: "報酬レンジ",
    below_market: "市場平均以下",
    market_avg: "市場平均",
    premium: "プレミアム",
    immediate_review: "要即時面談・見直し",
    monitor_engagement: "エンゲージメント監視",
    stable_retention: "安定・定着",
    realtime_metrics: "アクセスセキュリティとデータベースボリュームのリアルタイム指標",
    global_access: "グローバルアクセス",
    network_status: "ネットワーク状態",
    core_uptime: "稼働時間",
    hist_attrition: "過去の離職トレンド",
    satisfaction_risk_corr: "満足度とリスクの相関",
    immutable_audit: "変更不可な監査ログ",
    identifier: "識別子",
    unix_ts: "タイムスタンプ",
    integrity: "整合性",
    valid: "正常",
    failed: "エラー",
    sync_streams: "データストリーム同期中...",
    no_telemetry: "テレメトリは記録されていません。",
    identity_control_plane: "ID管理コントロールプレーン",
    master_record: "クエリを実行した全登録IDのマスタレコード",
    registry_matrix: "登録マトリクス",
    search_principal: "プリンシパル名を検索...",
    all_clearances: "全セキュリティ権限",
    user_principal_name: "ユーザー・プリンシパル名",
    auth_utc: "認証日時 (UTC)",
    status: "ステータス",
    clearance: "権限レベル",
    actions: "アクション",
    revoke: "無効化",
    active: "有効",
    revoked: "無効化済",
    handshake: "ハンドシェイク確立中...",
    no_identity: "登録されたIDが存在しません。",
    live_feed: "システムインフラ・セキュリティイベントのリアルタイムフィード",
    live_stream: "ライブストリーム",
    export_trail: "ログを書き出し",
    se_eng: "ソフトウェアエンジニア",
    se_sales: "営業担当",
    se_hr: "人事マネージャー",
    se_rs: "研究職・サイエンティスト",
    se_da: "データアナリスト",
    change_language: "言語切り替え",
    init_scenario: "シナリオを設定して\nデータを表示してください",
    subject: "本人",
    industry: "業界",
    dept_avg: "部門平均",
    ind_avg: "業界平均",
    transit: "通勤"
  }
};

interface LanguageContextProps {
  language: LanguageCode;
  setLanguage: (lang: LanguageCode) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextProps | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<LanguageCode>(() => {
    const saved = localStorage.getItem('appLanguage') as LanguageCode | null;
    if (saved && SUPPORTED_LANGUAGES.some(l => l.code === saved)) {
      return saved;
    }
    return 'en';
  });

  const setLanguage = (lang: LanguageCode) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: string): string => {
    const langTrans = translations[language];
    if (langTrans && langTrans[key]) {
      return langTrans[key];
    }
    // Fallback to English
    const engTrans = translations['en'];
    if (engTrans && engTrans[key]) {
      return engTrans[key];
    }
    return key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

export const LanguageSwitcher: React.FC<{ className?: string; dark?: boolean }> = ({ className = '', dark = false }) => {
  const { language, setLanguage, t } = useLanguage();
  const [isOpen, setIsOpen] = useState(false);

  const activeLang = SUPPORTED_LANGUAGES.find(l => l.code === language) || SUPPORTED_LANGUAGES[0];

  // Handle Escape key to close the dropdown
  useEffect(() => {
    if (!isOpen) return;
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        setIsOpen(false);
      }
    };
    window.addEventListener('keydown', handleKeyDown);
    return () => window.removeEventListener('keydown', handleKeyDown);
  }, [isOpen]);

  return (
    <div className={`relative z-50 ${className}`}>
      <button
        onClick={() => setIsOpen(!isOpen)}
        aria-haspopup="listbox"
        aria-expanded={isOpen}
        aria-label={t('change_language')}
        className={`flex items-center space-x-2 px-3 py-1.5 rounded-lg border text-xs font-semibold transition-all shadow-sm outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
          dark 
            ? 'bg-slate-900 border-slate-800 hover:bg-slate-800 text-slate-200 hover:border-slate-700' 
            : 'bg-white border-slate-200 hover:bg-slate-50 text-slate-700 hover:border-slate-300'
        }`}
        title={t('change_language')}
      >
        <img src={`https://flagcdn.com/${activeLang.countryCode}.svg`} width="16" alt={activeLang.name} className="inline-block rounded-sm shadow-sm" />
        <span className="hidden sm:inline">{activeLang.name}</span>
        <svg className={`w-3 h-3 transition-transform ${isOpen ? 'rotate-180' : ''}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M19 9l-7 7-7-7" />
        </svg>
      </button>

      {isOpen && (
        <>
          <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
          <div 
            role="listbox"
            aria-label="Available languages"
            className={`absolute right-0 mt-1.5 w-72 rounded-xl shadow-xl border z-50 p-2 transition-all animate-in fade-in slide-in-from-top-2 duration-150 ${
              dark 
                ? 'bg-slate-950 border-slate-800 text-slate-200' 
                : 'bg-white border-slate-150 text-slate-700'
            }`}
          >
            <div className="text-[10px] uppercase tracking-widest font-bold text-slate-400 dark:text-slate-500 px-2.5 py-1.5 border-b border-slate-100 dark:border-slate-900/50 mb-1.5">
              Select Language
            </div>
            <div className="grid grid-cols-2 gap-1">
              {SUPPORTED_LANGUAGES.map((lang) => (
                <button
                  key={lang.code}
                  role="option"
                  aria-selected={language === lang.code}
                  onClick={() => {
                    setLanguage(lang.code);
                    setIsOpen(false);
                  }}
                  className={`text-left px-2.5 py-2 text-xs flex items-center space-x-2 rounded-lg transition-colors outline-none focus-visible:ring-2 focus-visible:ring-indigo-500 focus-visible:outline-none ${
                    language === lang.code
                      ? dark ? 'bg-indigo-950 text-indigo-400 font-bold' : 'bg-indigo-50 text-indigo-700 font-bold'
                      : dark ? 'hover:bg-slate-900 text-slate-300' : 'hover:bg-slate-50 text-slate-600'
                  }`}
                >
                  <img src={`https://flagcdn.com/${lang.countryCode}.svg`} width="16" alt={lang.name} className="inline-block rounded-sm shrink-0 shadow-sm" aria-hidden="true" />
                  <span className="truncate leading-none">{lang.name}</span>
                </button>
              ))}
            </div>
          </div>
        </>
      )}
    </div>
  );
};
